#!/bin/bash
#PBS -N cherry_call_peaks
#PBS -l mem=100gb,ncpus=5
#PBS -o /home/atimms/pbs_logs
#PBS -j oe
#PBS -M andrew.timms@seattlechildrens.org
#PBS -m abe
# Pick your appropriate project ID for ‘-P’ below: 
#PBS -P 19833a08-f6fb-4bea-8526-8a79069da878

##run on cdbrmq queue i.e. qsub -q cdbrmq cherry_call_peaks_atac.pbs

##for homer section
##PBS -l mem=100gb,ncpus=5
# module load biobuilds
# module load homer/4.9.1

##for macs2
# module load local_python/3.7.6 
# source activate macs2

##for making bigwigs
##PBS -l mem=100gb,ncpus=5
module load biobuilds

##looking at adult scATAC and doing lots of test
cherry_human_scatac_call_peaks_0720_cyb.py

##running a bunch of ways for correlation
# cherry_scatac_call_peaks_0820_cyb.py