#!/bin/bash
#PBS -N dave_work
#PBS -l mem=20gb,ncpus=1
#PBS -o /home/atimms/pbs_logs
#PBS -j oe
#PBS -M andrew.timms@seattlechildrens.org
#PBS -m abe
#PBS -P 2cf4ba3b-f9ef-4cfc-a2c1-be85f5db6730
echo 'work'

## #PBS -l mem=200gb,ncpus=20
##dave zf sex analysis 0920
# module load biobuilds/2017.11
# module load gcc/6.1.0 ##for homozygosity_mapping_cybertron
# dave_zf_sex_0920_cyb.py

##dave enu exomes 0920
# module load biobuilds/2017.11
# module load gcc/6.1.0 ##for homozygosity_mapping_cybertron
# dave_enu_exomes_0920_cyb.py

##dave zf sex analysis 1220
# module load biobuilds/2017.11
# module load gcc/6.1.0 ##for homozygosity_mapping_cybertron
# dave_zf_sex_1220_cyb.py

##genome analysis dave/lisa 0321
# module load java/11.0.10 ##for snpeff part
# dave_lisa_chd_kf_genomes_0321_cyb.py

##dave/chunyue zf hom mapping 0321
# #PBS -l mem=120gb,ncpus=10
# module load biobuilds/2017.11
# module load gcc/6.1.0 ##for homozygosity_mapping_cybertron
# chunyue_abcb11b_recessive_0321_cyb.py
##and for the rnaseq analysis
# chunyue_abcb11b_rnaseq_0521_cyb.py

##dave/lisa genomes 0821
#PBS -l mem=20gb,ncpus=1
# dave_lisa_chd_genomes_annovar_0821_cyb.py

##dave_pkd_modifier_0921
## #PBS -l mem=200gb,ncpus=20
module load biobuilds/2017.11
module load gcc/6.1.0 ##gcc version used to make bedtools using in homo mapping
dave_pkd_modifier_0921_cyb.py



