#!/bin/bash
#PBS -N ghayda_exomes
#PBS -l mem=200gb,ncpus=20
#PBS -o /home/atimms/pbs_logs
#PBS -j oe
#PBS -M andrew.timms@seattlechildrens.org
#PBS -m abe
#PBS -P 7983b837-c948-4788-96af-f9e199a817a2
echo 'work'

##testing exome pipleine
module load java/1.8.0_121 
module load biobuilds/2016.11
module load vt/0.5772-60f436c3 
module load mono/5.10.1.47
module load Pisces/5.1.6.54
run_dobyns_exomes_cybertron.py