#!/bin/bash
#PBS -N fetal_genome
#PBS -l mem=50gb,ncpus=2
#PBS -o /home/atimms/pbs_logs
#PBS -j oe
#PBS -M andrew.timms@seattlechildrens.org
#PBS -m abe
# Pick your appropriate project ID for ‘-P’ below: 
#PBS -P 0f241fcd-0dd3-491c-acac-15c6cff1c880

echo 'work'
module load java/1.8.0_121 

##analysis 

##for bwa: #PBS -l mem=200gb,ncpus=20
##for mutect:  #PBS -l mem=50gb,ncpus=2
source activate MF
jimmy_fetal_genomes_mf_0321_cyb.py


