#!/bin/bash
#PBS -N rnaseq_analysis
#PBS -l mem=200gb,ncpus=20
#PBS -o /home/atimms/pbs_logs
#PBS -j oe
#PBS -M andrew.timms@seattlechildrens.org
#PBS -m abe
# Pick your appropriate project ID for ‘-P’ below: 
##vishal
#PBS -P ad555671-9e4f-4764-b566-34fb8bd7d5df 

##dave
## #PBS -P 2cf4ba3b-f9ef-4cfc-a2c1-be85f5db6730 ##dave

echo 'work'
module load java/1.8.0_121
module load biobuilds/2017.11

rnaseq_pipeline_cybertron_v0.py
